const TOGGLE_MUSIC = 'TOGGLE_MUSIC';
const TOGGLE_SOUND = 'TOGGLE_SOUND';
const CHANGE_SIZE = 'CHANGE_SIZE';

const SET_LEVEL = 'SET_LEVEL';
const SET_SCORE = 'SET_SCORE';
const FINISH_GAME = 'FINISH_GAME';

export {
  TOGGLE_MUSIC, TOGGLE_SOUND, CHANGE_SIZE, SET_LEVEL, FINISH_GAME, SET_SCORE,
};
