const TOGGLE_MUSIC = 'TOGGLE_MUSIC';
const TOGGLE_SOUND = 'TOGGLE_SOUND';
const CHANGE_SIZE = 'CHANGE_SIZE';

const TURN_UP_MUSIC = 'TURN_UP_MUSIC';
const TURN_UP_SOUND = 'TURN_UP_SOUND';

const TURN_DOWN_MUSIC = 'TURN_DOWN_MUSIC';
const TURN_DOWN_SOUND = 'TURN_DOWN_SOUND';

const SET_LEVEL = 'SET_LEVEL';
const SET_SCORE = 'SET_SCORE';
const FINISH_GAME = 'FINISH_GAME';

const TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE';

export {
  TOGGLE_MUSIC, TOGGLE_SOUND, CHANGE_SIZE, SET_LEVEL, FINISH_GAME, SET_SCORE,
  TURN_UP_MUSIC, TURN_UP_SOUND, TURN_DOWN_MUSIC, TURN_DOWN_SOUND, TOGGLE_LANGUAGE,
};
